import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/app/components/main/Header/Header';
import cn from 'classnames';
const inter = Inter({ subsets: ['latin'] });
import Logo from '../public/logo-black-transparent-hat-3.png';
import { headerMoto } from '@/data/header-moto';
import Footer from '@/app/components/main/Footer/Footer';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          inter.className,
          'container mx-auto min-h-screen flex flex-col'
        )}
      >
        <Header logo={Logo} logoWidth={170} headerMoto={headerMoto} />
        <main className='className="flex-grow"'>{children}</main>
        <Footer className='mt-auto' />
      </body>
    </html>
  );
}
